# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'CodyChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodyChat
  pod 'Alamofire', '~> 5.8.0'

  target 'CodyChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodyChatUITests' do
    # Pods for testing
  end

end
